### ISSUE TITLE
Missing recipes/crash

### ISSUE THREAD

**Issue by UnNinja** [TheCBProject/Translocators#1]
Nothing seems to have a recipe (or at least none show in JEI). I was going to them in myself with minetweaker until you could fix, but when I placed one in-world it crashed. http://pastebin.com/CBemgqiX
Tested with both the latest versions on curse and on the [chickenbones site](http://chickenbones.net/Pages/links.html)

**Comment by covers1624** [comment]
I'll have a new version on curse soon.
