### ISSUE TITLE
[1.9.4] java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by Xiaminou** [TheCBProject/Translocators#1]
Crashed the first time I tried to transfer items between 2 ender chests with translocators. When I logged back into my singleplayer everything was fine.

Crash Report: http://pastebin.com/MPRYeW7A

**Comment by covers1624** [comment]
Odd, seems the AccessTransformer wasn't applied.. probably just a fluke, open a new issue if it happens again as it works fine in BTM.

**Comment by Xiaminou** [comment]
That's what I thought, will do.
