### ISSUE TITLE
[MC 1.10.2, translocators .49] placing and using fluid translocators not working properly.

### ISSUE THREAD

**Issue by Crusaderkvw** [TheCBProject/Translocators#11]
So the translocators DO place now(thanks for that fix!) but now I have the problem that whenever I place 2 fluid translocators on any fluid handling tank(enderIO tank, tinker's smeltery etc) and I try to start moving liquids it does so only a very small amount before the translocators "break" and drop as items.  

Tinker's smeltery: exactly 1 ingot before they break.
EnderIO tank: 200mb before they break.  

Before posting this issue I checked on [this thread](https://github.com/TheCBProject/Translocators/issues/3) and there you say that the translocators should work. going to try and make a short gif so you can see what is going on.

**Comment by lillelilje** [comment]
@covers1624 Any ideas? I have the same issue.

**Comment by covers1624** [comment]
Found the issue, hopefully its fixed.
