### ISSUE TITLE
Fluid Translocators not working with Tinkers Smeltery 1.10.2

### ISSUE THREAD

**Issue by e30Birdy** [TheCBProject/Translocators#13]
It works for one ingot and then it falls off

**Comment by covers1624** [comment]
@bonii-xx Any ideas?

**Comment by gigabit101** [comment]
I think the fluid cap gets removed after it dose one cast

**Comment by Sinfuldeity** [comment]
I can confirm, translocators work for 1 ingot/block on a smeltery before breaking and falling as drop items. just tried this on Sky Factory 3

**Comment by bonii-xx** [comment]
TiC issue, fixed next version with https://github.com/SlimeKnights/TinkersConstruct/commit/82cc1dfa36a697b522456814dbf6d81134c2c329

**Comment by wooby6** [comment]
This also occurs with Ender IO tanks as well, but they break off when the tank is empty or close to that

**Comment by GreatOrator** [comment]
Confirmed as of now:
Tinkers v2.6.3 and Translocators 2.1.3.52

Looks basically like the translocators think the tinkers block has briefly disappeared which causes the fluid translocators to fall off.

**Comment by covers1624** [comment]
Found the issue, hopefully its fixed.
