### ISSUE TITLE
Fluid Translocator crashes the game when used with Immersive Engineering

### ISSUE THREAD

**Issue by jawsawn** [TheCBProject/Translocators#17]
https://gist.github.com/JAWSAWN/aecb7f3140101bf352758fa189fcf0d4
https://gist.github.com/JAWSAWN/b70cc8edd578a25ddfe5740e35ed9d93

It crashes

**Comment by covers1624** [comment]
This might be an immersive engineering issue. This is IE crashing on rendering something when it shouldn't.

**Comment by jawsawn** [comment]
I talked to BluSumrise about this. It appears to be on translocators end. When placed next to a IE tank

**Comment by covers1624** [comment]
Please try build 50 from http://chickenbones.net/Pages/links.html
