### ISSUE TITLE
Can't use the latest version in a curse modpack due lack of licence

### ISSUE THREAD

**Issue by jawsawn** [TheCBProject/Translocators#18]
https://docs.google.com/spreadsheets/d/1BX4fFRnfANPvWjnkPlfGx03RlBq5JkmuBvwEO_6gdbE/edit#gid=0

Translocators have no licence to be in a curse modpack, but translocators as a mod exists in the curse. But the latest version 3.51 doesn't exist in it which fixes a big bug with the liquid translocator crash.

Can you please either update the version 3.51 to curse or give license?

**Comment by gigabit101** [comment]
Its on Curse.... https://minecraft.curseforge.com/projects/translocators-1-8

**Comment by gigabit101** [comment]
o0 my bad did not see the version thing

**Comment by jawsawn** [comment]
BUT version Translocators 1.10.2-2.1.3.51-universal doesnt exist in there
which fixes a crash bug

**Comment by gigabit101** [comment]
yes @covers1624 needs to push it to curseforge
