### ISSUE TITLE
[1.10.2] Ticking block entityCrash on Server

### ISSUE THREAD

**Issue by DeadSix27** [TheCBProject/Translocators#19]
Version: Translocators-1.10.2-2.1.3.52-universal.jar

Also reported on SolarFluxReborn (as I have no idea which of them both causes this)
https://minecraft.curseforge.com/projects/solar-flux-reborn/issues/38

Stacktrace: http://pastebin.com/5Z2L6inf

**Comment by TehenoPengin** [comment]
It may be because there is TileItemTranslocator in the place of solar panel; Not sure why, but that seems to be the case here...

**Comment by DeadSix27** [comment]
@MrDimkasStudio Very odd, world corruption?

**Comment by TehenoPengin** [comment]
Idk...

**Comment by covers1624** [comment]
If this happens again open a new issue.
