### ISSUE TITLE
[Request] Remove dependency on CCC

### ISSUE THREAD

**Issue by mezz** [TheCBProject/Translocators#2]
Translocators is a great simple mod, but it seems really weird that it needs a coremod.
Is is possible to make Translocators stand alone, without CodeChickenCore?

**Comment by gigabit101** [comment]
I do agree with this request and It would be a nice change

**Comment by covers1624** [comment]
I'll look in to it, atm it needs a lot of what is in ccc, inventory and fluid stuff, then it needs the ccl render pipe as well.

**Comment by covers1624** [comment]
Things are changing and this is no longer an issue.
