### ISSUE TITLE
Item translocator is unable to be placed on EnderStorage chests

### ISSUE THREAD

**Issue by chasminimus** [TheCBProject/Translocators#27]
In the 1.7.10 version, an item translocator cannot be placed on the vanilla ender chest. However, it _can_  be placed on the EnderStorage ender chest. In the 1.11.2 version, they cannot be placed on the EnderStorage chests, you open the chest instead.

Using `Translocators 1.11.2-2.2.0.59-universal` with `Ender Storage 1.11.2-2.3.0.112-universal` on MC 1.11.2.

**Comment by covers1624** [comment]
This will be fixed in time, EnderStorage moved to a pure capability implementation, Translocators will soon be following with a massive update and Micropart support.
