### ISSUE TITLE
[1.10.2] Cannot use Fluid Translocator on Tinkers

### ISSUE THREAD

**Issue by HendrikJ79** [TheCBProject/Translocators#3]
I am not sur if this is the right place.

I cannot use Fluid Translocators to poor out liquids from a tinkers drain into a casting table or basin.
Can't find any errors, perhaps not integrated yet?

**Comment by covers1624** [comment]
Yes, Translocators does not support the new capability system, i am yet to move it over, i will move it over when i move Translocators to be Multipart compatable witch will need a full rewrite anyway,

**Comment by DrZed** [comment]
They also don't work with RFTools Tanks, Extra Utils Drums, or any mod tank that implements IFluidContainer (I think it was called)

**Comment by covers1624** [comment]
IFluidContainer stuff is fine, it is the capability stuff that it does not work on.

**Comment by covers1624** [comment]
Fluid translocators should now wok with everything.
