### ISSUE TITLE
1.11.2 Invisible Translocators Until Placed

### ISSUE THREAD

**Issue by Darkosto** [TheCBProject/Translocators#30]
Heya Covers,

The invisible translocators issue persists in 1.11.2. Is this something you may be able to take a look at?

Thank you!
Darkosto

**Comment by covers1624** [comment]
WKL:AShjfioaweklasjfdi I swore i fixed this.. what. the. fuck..

**Comment by Darkosto** [comment]
I'll show you on stream right now! LUL

**Comment by covers1624** [comment]
If this happens again, please open a new issue, i haven't seen this in 1.12 at all.
