### ISSUE TITLE
Abandon?

### ISSUE THREAD

**Issue by JoeSGT** [TheCBProject/Translocators#33]
Hello i was wondering if this mod is abandon because 1.12.X been out for a while now and it doesn't seem that this mod is being updating 
please let me know and sorry for asking for something like this 

Thanks

**Comment by covers1624** [comment]
Absolutely not! I've just been juggling life, modding and other projects that i work on for fun. I recently posted an update to twitter. https://twitter.com/covers1624/status/933727225609797632
