### ISSUE TITLE
Item transfer nodes not moving more than one item

### ISSUE THREAD

**Issue by Spikeal** [TheCBProject/Translocators#36]
Hey, I am running this on 1.12.2, and the item translocator with a diamond nugget is not regulating multiple items, it will only regulate the first item in the inventory it is pulling from, am I missing something, or is this intentional?

**Comment by covers1624** [comment]
You mean it will only regulate the first thing selected in the translocator, or it will only access the first slot of the chest connected?

**Comment by Spikeal** [comment]
the first item in the chest, so if I have a stack of 64 redstone blocks, and then a stack of 64 cobblestone, and I have the regulator set to  keep 3 redstone blocks, and 4 cobblestone, it will only regulate whichever one is in the first filled slot, ignoring empty slots

**Comment by Spikeal** [comment]
here are some screenshots of how I am testing it, i have tried it with different items to see if that was the problem, but this does not seem to be the case, I have both redstone, and a diamond nugget on the recieving translocator
![2018-04-01_21 45 41](https://user-images.githubusercontent.com/16421401/38179908-46216964-35f6-11e8-850b-6db76125b4ff.png)
![2018-04-01_21 45 49](https://user-images.githubusercontent.com/16421401/38179909-4643a65a-35f6-11e8-88de-e1149feb590e.png)
![2018-04-01_21 45 57](https://user-images.githubusercontent.com/16421401/38179910-46809178-35f6-11e8-9a7f-774237ee1518.png)
![2018-04-01_21 46 07](https://user-images.githubusercontent.com/16421401/38179911-46ac4598-35f6-11e8-9778-0a2909286661.png)
![2018-04-01_21 46 14](https://user-images.githubusercontent.com/16421401/38179912-46d8d40a-35f6-11e8-9748-99627db58cb2.png)

**Comment by orville94Bailey** [comment]
Is this issue still in the current version of the mod?  I'm seeing it in FTB Contiuum.

**Comment by covers1624** [comment]
I think i know the cause of this, will work on a fix in the next few days.

**Comment by covers1624** [comment]
Please test with http://chickenbones.net/maven/codechicken/Translocators/1.12.2-2.5.0.74/
