### ISSUE TITLE
Glowstone Translocators Voiding Items

### ISSUE THREAD

**Issue by Vyraal1** [TheCBProject/Translocators#37]
At first I thought this was an Extended Crafting issue or a mod pack related issue, hence this https://github.com/Darkosto/SevTech-Ages/issues/1649

But for some reason it occurred again with Immersive Engineering metal presses, here's another video of it voiding, iron ingots going into a metal press, it happens for some reason only when the translocators are next to each other.

https://streamable.com/3xqre

**Comment by codewarrior0** [comment]
Can confirm, translocator deletes items when inserting into metal press due to metal press only accepting limited numbers and/or fixed stack-sizes depending on the installed press mold.
