### ISSUE TITLE
[1.12.2] Transposers randomly disappearing after a while

### ISSUE THREAD

**Issue by Atskadan** [TheCBProject/Translocators#38]
I have a set of fluid transposers attached to a lightwell from Astral Sorcery. After some time, they will simply be gone, and fluid transfer will halt. 
I've tested a few things; the disappearance isn't caused by the lightwell's crystal breaking, and it doesn't seem to happen when chunks unload or anything like that. I can't see any reason for it, but it will happen consistently after some amount of time. I've had them last for a very long time (5~ hours) and some that will break in less than an hour.
The translocators are not dropped as items when this happens.

Edit: This also happens with item transposers. :/

**Comment by covers1624** [comment]
I think this is actually related to chunk unloading, please show me a screenshot of your setup with the chunk overlay on.

**Comment by Atskadan** [comment]
https://i.imgur.com/tlITHVO.jpg
tank is from evilcraft

**Comment by Snownee** [comment]
Can confirm this issue while playing FTB Continuum

**Comment by covers1624** [comment]
So, this might be an FMP issue, does closing and opening the world make them 'reappear'?

**Comment by Snownee** [comment]
No, but sometimes they disappear after re-opening the world.

**Comment by covers1624** [comment]
are you 100% sure that after they disappear, reloading the world does not make them reappear? If that is the case, then this is a far deeper issue..

**Comment by covers1624** [comment]
Actually, can i get a full log file, from a launch where the parts were removed please?

**Comment by Snownee** [comment]
I can' t reproduce it now, need some time to figure out.

**Comment by tsurezuregusa** [comment]
I am having the same problem, and it is reproducible in some cases. 

In this spot, every time I place translocators, log out and back in, they disappear.

![2018-05-30_17 06 18](https://user-images.githubusercontent.com/589440/40707717-82cf4232-642c-11e8-932b-59314dc112c0.png)
![2018-05-30_17 06 28](https://user-images.githubusercontent.com/589440/40707726-85dfd9f0-642c-11e8-8199-7f72a31e633e.png)
![2018-05-30_17 07 05](https://user-images.githubusercontent.com/589440/40707730-87aae068-642c-11e8-983c-7534c0678c8f.png)

These are the logs from just logging in adding the translocators and relogging:
[debug.log.gz](https://github.com/TheCBProject/Translocators/files/2052979/debug.log.gz)
[latest.log.gz](https://github.com/TheCBProject/Translocators/files/2052981/latest.log.gz)

Here is the chunk overlay.
![2018-05-29_20 38 49](https://user-images.githubusercontent.com/589440/40707746-8f1c8ef0-642c-11e8-9e02-fbffb608130b.png)
![2018-05-29_20 41 01](https://user-images.githubusercontent.com/589440/40707753-92cb4f46-642c-11e8-8f63-49ba874be54c.png)
![2018-05-29_20 42 26](https://user-images.githubusercontent.com/589440/40707757-9697534a-642c-11e8-9caa-01981bf8c296.png)

Translocators placed to go to the chest above the storage drawer also disappeared, but the one to the left never has. I have gotten it with vanilla chests only as well.

Another translocator that has never disappeared.
![2018-05-29_20 54 35](https://user-images.githubusercontent.com/589440/40707761-9908faa2-642c-11e8-83f7-c804d6397e41.png)

I have tried some in another world and have not been able to reproduce it.

**Comment by covers1624** [comment]
Interesting, can i get your entire instance? World, mods, config, Feel free to poke it to me on discord if you don't want to post it here.

**Comment by tsurezuregusa** [comment]
Sure, how do I do that. It's ~400MB with the mods (my own pack).

Edit: I emailed you a link to dropbox.

**Comment by covers1624** [comment]
I suggest Google Drive or Dropbox.

**Comment by PooThee** [comment]
Yeh, I'm also having the same issue on FTB Continuum

**Comment by covers1624** [comment]
I'm currently in the middle of a play through of FTB Continuum, i haven't come across this yet, but its easier to debug in the wild, i will check out tsurezuregusa pack the provided some time next week.

**Comment by covers1624** [comment]
Cleaning this in to a single issue: TheCBProject/ForgeMultipart#29

**Comment by jk1895** [comment]
Hello,
I have the same issue in the Foolcraft 3 modpack. They just disappear....
Greetings
