### ISSUE TITLE
Crash with Translocators for 1.10.2

### ISSUE THREAD

**Issue by homemmakako** [TheCBProject/Translocators#4]
When using translocators for 1.10.2 (version 2.1.3.34) the game crashes on startup
-   CCC version: 2.3.5.91
-   CCL version: 2.4.3.124
-   Forge version: 12.18.2.2113

[Crash Log](http://pastebin.com/DFFa5UMD)

**Comment by covers1624** [comment]
You have a duplicated CCL, Remove the older version from /mods/1.10.2 and ensure there is only one version inside your /mods folder.

**Comment by homemmakako** [comment]
Ohh... ok, my bad. Didn't expect that, since I'm using the curse launcher. Thanks 😝
