### ISSUE TITLE
Item Translocator can't pull items out of an Extra Utilities 2 Crusher

### ISSUE THREAD

**Issue by RyanP1991** [TheCBProject/Translocators#42]
Using version 1.12.2 - 2.5.0.73, I made a set up for ore processing going chest - translocator - crusher - translocator - chest. Whenever I put ore in to the chest the top translocator will happily pull the ore out of the chest and put it in the crusher, but when it's finished processing the bottom translocator isn't able to pull out the crushed ores.

**Comment by covers1624** [comment]
I made some changes yesterday that might affect this, please try with http://chickenbones.net/maven/codechicken/Translocators/1.12.2-2.5.0.74/

**Comment by covers1624** [comment]
Verified this myself, Fixed via: https://github.com/TheCBProject/Translocators/commit/71215060ebdb9f7fc7596e1a7fbf9d4b97a1f1dc

**Comment by RyanP1991** [comment]
Sorry for not replying sooner due to time zones and was asleep, thank you for the quick reply.
