### ISSUE TITLE
Translocators vanished from world, when chunks unloaded.

### ISSUE THREAD

**Issue by ghost** [TheCBProject/Translocators#44]
FTB Revelations V2.3
Translocators V2.5.0.73
Forge Mod Loader V8.0.99.99
Minecraft Forge V14.23.4.2738
Jave 8u181 x64

I had just set up a great system for automating the creation of Slates for Blood Magic using translocators in my claimed but not chunk loaded chunks.   I left the area of the chunks for a few minutes and came back, all of the Translocators were GONE.

An input Chest -> T1/T2 -> Blood Altar -> T3/T4 -> output Chest.  This particularly nice because T3 had a diamond chip applied to limit the extraction from the blood altar for each type of more advancedd Slate.  This ensured that it made 32 Blank Slates, then 32 Reinforced Slates, 32 Imbued Slates, and so on.

![2018-08-03_01 40 45](https://user-images.githubusercontent.com/7958470/43633643-ae1bfaa6-96be-11e8-9c94-ba41203ff032.png)
![2018-08-03_01 41 15](https://user-images.githubusercontent.com/7958470/43633644-ae38319e-96be-11e8-8ad4-3e78018248c3.png)

(Translocaters were positioned right between the chests and the blood altar, on both sides)

**Comment by covers1624** [comment]
This issue was fixed. https://github.com/TheCBProject/ForgeMultipart/issues/29
