### ISSUE TITLE
Translocatior won't push to a storage drawer with a void upgrade

### ISSUE THREAD

**Issue by TheSaucyWelshman** [TheCBProject/Translocators#45]
Title

Forge: 14.23.4.2759

Translocators: 1.12.2-2.5.1.77-universal

Chicken Lib: 1.12.2-3.2.1.351-universal

Forge Multipart: 1.12.2-2.5.0.71-universal

Storage Drawers: 1.12.2-5.3.7

Chameleon: 1.12-4.1.3

Tested in a fresh instance with JEI being the only other mod.

**Comment by covers1624** [comment]
Nothing i can do here, limitation of the inventory API, if StorageDrawers's devs have any suggestions i'd be happy to take them on board moving forward.

**Comment by Dustybonss** [comment]
Late but i was having this issue and is still present today in 1.12.2, to get around this problem i am using an Immersive engineering "Item Router" with no filters set inside of it, if you translocator into the item router and then have it next to a drawer or drawer controller it acts as a middle man and allows for items to pass into Void drawers. The P2P tunnel on top is attached to multiple drawer controllers, which acts the same as if it was just a drawer controller.

<img width="915" height="903" alt="Image" src="https://github.com/user-attachments/assets/c80a34b9-8a69-45d6-8b2f-cabb3292201a" />
