### ISSUE TITLE
Deleting Items?

### ISSUE THREAD

**Issue by knoxhack** [TheCBProject/Translocators#48]
## Bug Report

I have a cobblestone generator teir 5 that makes 1 cobblestone every tick. Using the translocator to move the cobblestone to be crushed into gravel. Unfortunatly it isn't stacking rather anything I put in the crusher automatically deletes cobblestone in there if there is more than 1 cobblestone. 
Video: https://youtu.be/jQVPDpusbHA

## Steps to Reproduce (for bugs)

1. Have a teir 5 cobble gen, extra utilites 2 crusher, 2 item translocators
2. place translocators on the right and left side (blocks left and right, not your left and right) of the cobble gen and crusher (depending on how you place them)
3. Have the translocator that is on the crusher have it only look for cobblestone (if needed)
4. Push the translocator button on the trans locator and should be going really fast and stacking (as it should)

## Logs

* Client/Server Log: https://pastebin.com/AsGWgW7z Don't have unlimited space so I don't know if this helps.
* Crash Log: 

## Client Information

* Modpack Version: StoneBlock-1.022r1
* Server/LAN/Single Player: SIngle Player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by covers1624** [comment]
If it doesn't happen with a vanilla chest or furnace, its not my bug and would likely be on XU2's end. The Item Translocator doesnt care what inventory it is, only that it has the IItemHandler capability, i highly doubt this is something in Translocators.

**Comment by covers1624** [comment]
I believe this is fixed by https://github.com/rwtema/Extra-Utilities-2-Source/commit/993955750a3547a1d68738a222bcc72e3430cf4b @rwtema can you confirm at all please?

**Comment by covers1624** [comment]
Confirmed this was fixed in ExtraUtilities.

**Comment by rwtema** [comment]
Yep is weird old bug that's been present in the code for years but was only triggered by a change a week ago. Fixed now.
