### ISSUE TITLE
[Crash] ArrayIndexOutOfBoundsException v2.5.1.77

### ISSUE THREAD

**Issue by Moustik2002** [TheCBProject/Translocators#53]
Hi, got a client crash on modpack ultimate alchemy. 
It happens while i was adding a liquid translocator to an existing pair to insert lava on a ExtraU2 iron drum.

You'll find crash report down here : https://pastebin.com/3wuHRPDy

No way to get back to my save :'(

**Comment by covers1624** [comment]
https://github.com/TheCBProject/Translocators/pull/52
