### ISSUE TITLE
Crash when moved with Moving Wand

### ISSUE THREAD

**Issue by ShayBox** [TheCBProject/Translocators#56]
Move a translocator with a movement want, it will drop the items when you re-place them then crask before you can pick them up

**Comment by covers1624** [comment]
Please provide a crash report, this is like calling a mechanic about your car, explaining the problem, then hanging up and expecting it to be fixed.

**Comment by ShayBox** [comment]
Well it's more taking your car to a mechanic telling them the problem and how to reproduce it and expecting them to fix it, expecting the car owner to give diagnostic reports is not normal, but that's the problem with hyperbole, that is normal in this case, I just didn't get a crash report to report originally, I had to enable the show logs in the launcher to get it.
https://paste.ee/p/JYjUk

**Comment by LemADEC** [comment]
ProjectE is part of the issue, reproduce without it or report it to them

**Comment by covers1624** [comment]
Your paste has expired, please use a long lasting paste service such as [gist](https://gist.github.com).
