### ISSUE TITLE
[1.10.2] Invisible Translocators

### ISSUE THREAD

**Issue by ghost** [TheCBProject/Translocators#6]
Not sure what's going on, but both translocators are invisible in any inventory or menu, and can't be placed in the world. I've tried with the latest unstable build with the same result. Using forge build 2122, if that helps.

**Comment by covers1624** [comment]
Attempt to place one on a chest, there seems to be issues with the model not loading properly until placed in world. There are also issues in the back end stoping me from supporting some tiles as forge is missing methods for me and will be added in 1.11

**Comment by xenoflot** [comment]
Confirmed still a problem with translocators-1.10.2-2.1.3.47-universal and forge 2185.

**Comment by Crusaderkvw** [comment]
Using the latest forge and translocators and I do not only have the invisible bug but the game crashes when I try to place it in the world. getting this crash: http://pastebin.com/bpjA0mJi

**Comment by covers1624** [comment]
Can you open an issue for that other crash, the main issue here seems to be something with the ccl model pipe, I've noticed it several times but sadly I can't figure it out, I'll do more investigating.

**Comment by Crusaderkvw** [comment]
Sure, thought I'd post it here first since I didn't know it was the same crash. going to post a new issue then :D

**Comment by xenoflot** [comment]
Tested just now with a stripped-down pack; only JEI and Translocators.  Bug-testing on NYE! I'm such a nerd \o/

* Translocators are _invisible_ in JEI *on a freshly-booted client*.
* *JEI-Spawned* translocators are _invisible_ in the inventory *on a freshly-booted client*.
* I forgot to test if crafted translocators are invisible, sorry.

* Once placed on the side of a chest, translocators become _visible_ in the world, in the inventory and in JEI.
* Disconnecting from the server and reconnecting, they're still _visible_.

I hope that helps you track it down.

Pretty: http://i.imgur.com/qTcdboU.png

translocators-1.10.2-2.1.3.49-universal
codechickencore-1.10.2-2.4.0.100-universal
codechickenlib-1.10.2-2.5.0.178-universal
jei-1.10.2-3.13.6.393
forge 2185

**Comment by covers1624** [comment]
Thanks for your investigation but i am able to reproduce this in dev sinde the initial 1.8.8 update i did. Its a really strange issue and may have something to do with the quirks of the 1.8 update.

**Comment by covers1624** [comment]
Also, your not a nerd for doing bug testing on NYE :P im currently rewriting parts of ProjectRed's lamp rendering :D

**Comment by xenoflot** [comment]
Nah, we're nerds. We just feel that being a nerd isn't a bad thing :)

**Comment by covers1624** [comment]
Heh, i suppose. i see it as im doing what makes me happy so idgaf on what other people think of it.

**Comment by covers1624** [comment]
I havent seen this happen in a while. If its still an issue, open a new issue.
