### ISSUE TITLE
Cross-mod crash w/ ActuallyAdditions and Cooking for Blockheads

### ISSUE THREAD

**Issue by MrPipperz** [TheCBProject/Translocators#7]
Using latest AA release (r88), Translocators 1-8 latest release (2.1.3.34) and latest CCC libraries, and latest Cooking for Blockheads release (4.2.26). Using latest forge #2171 (same crash results with #2099)

Attaching a Translocator to an Item Phantomface which is already bound to a CfBH kitchen multiblock (any of them seemingly, have tested several, same result) results in a crash a few ticks later.

Have tested in a new custom instance with only the required mods and libraries loaded (well, plus Blood Magic by mistake, but I doubt it matters), same result.

Does Translocators make a check against the block the player is attempting to place a Translocator on? It seems Translocators cannot normally be placed on CfBH kitchen multiblocks.

Within the same instance and session I checked that the Phantomfaces were able to route items to the CfBH blocks with vanilla hoppers prior to attempting to place a Translocator on the Phantomface, this was successful each time.

Attempting to reload the world results in the same crash, effectively resulting in a "bugged" save.

I realize this is an odd corner case, but I thought you'd appreciate a report.

Happy holidays!
[crash-2016-12-04_08.39.07-server.txt](https://github.com/TheCBProject/Translocators/files/629659/crash-2016-12-04_08.39.07-server.txt)
[crash-2016-12-04_09.53.18-server.txt](https://github.com/TheCBProject/Translocators/files/629660/crash-2016-12-04_09.53.18-server.txt)

**Comment by covers1624** [comment]
Not on me, probably has been fixed in actually additions.
