### ISSUE TITLE
1.16.5 version needs cb-Multipart, but downloading it gives an error

### ISSUE THREAD

**Issue by grandogarndo** [TheCBProject/Translocators#72]
The error says: needs language provider scorge:3.1 or above to load

**Comment by covers1624** [comment]
As stated on the [CBMultipart CurseForge page](https://www.curseforge.com/minecraft/mc-mods/cb-multipart). [Scorge](https://www.curseforge.com/minecraft/mc-mods/scorge) is a required dependency.
