### ISSUE TITLE
Server crash with translocators

### ISSUE THREAD

**Issue by Saereth** [TheCBProject/Translocators#8]
MC 1.10.2
Translocators-1.10.2-2.1.3.44-universal.jar

This is happening in other versions as well, if you put redstone on a translocator and run a redstone wire to it, server crashes
setup:
http://imgur.com/a/zkLiF

crashlog:
http://hastebin.com/ixiyuqudet.pl

**Comment by covers1624** [comment]
Fixed with latest build.
