### ISSUE TITLE
[1.20.1] Translocator has CB Multipart dependency which doesn't currently exist in version 1.20.1

### ISSUE THREAD

**Issue by Staegrin** [TheCBProject/Translocators#82]
![image](https://github.com/TheCBProject/Translocators/assets/8494635/e9906313-9116-4066-8e36-fea47e929c07)

Translocators has CB Multipart dependency which doesn't currently exist in version 1.20.1

Versions:
minecraft 1.20.1
Neoforge 47.1.76
Translocators-1.20.1-2.6.0.86-universal.jar
CodeChickenLib-1.20.1-4.4.0.509-universal.jar

**Comment by covers1624** [comment]
https://github.com/TheCBProject/CBMultipart/issues/160
